version: "2"
plugins:
  checkstyle:
    enabled: true
    config:
      file: checkstyle.xml

  sonar-java:
    enabled: true
    config:
      sonar.java.source: "15"
    checks:
      squid:S1068:
        enabled: false
      squid:S00112:
        enabled: false
      squid:S00107:
          enabled: false

  pmd:
    enabled: true
    config:
      file: pmd.xml
    checks:
      DataClass:
        enabled: false
      AtLeastOneConstructor:
        enabled: false 
      LawOfDemeter:
        enabled: false 
      JUnitTestsShouldIncludeAssert:
        enabled: false 
      BeanMembersShouldSerialize:
        enabled: false
      CommentDefaultAccessModifier:
        enabled: false
      SignatureDeclareThrowsException:
        enabled: false
      ExcessiveImports:
        enabled: false
      DefaultPackage:
        enabled: false 
      CallSuperInConstructor:
        enabled: false
      DataflowAnomalyAnalysis:
        enabled: false
      OnlyOneReturn:
        enabled: false
      AvoidInstantiatingObjectsInLoops:
        enabled: false
      AvoidFieldNameMatchingMethodName:
         enabled: false
      AvoidCatchingGenericException:
        enabled: false

checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 550
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 40
  method-lines:
    config:
      threshold: 55
  nested-control-flow:
    config:
      threshold: 5
  return-statements:
    config:
      threshold: 5
  similar-code:
    config:
      threshold: 60
  identical-code:
    config:
      threshold: 60

exclude_patterns:
  - "/web/**"
  - "/api/src/test/**"

