version: '3'
services:
  web:
    image: confeti/web
    expose:
      - 80
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    image: confeti/api
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - API_URL=http://localhost:8080
      - WEB_URL=http://localhost:3000
      - CASSANDRA_SESSION_NAME=confeti_session
      - CASSANDRA_KEYSPACE_NAME=confeti
      - CASSANDRA_RF=1
      - CASSANDRA_DURABLE=true
      - CONFETI_LOCAL_DB=${CONFETI_LOCAL_DB}
      - ASTRA_PASSWD=${ASTRA_PASSWD}
      - ASTRA_CREDS=${ASTRA_CREDS}

  cassandra:
    image: cassandra:3.11.8
    ports:
      - 7000:7000
      - 9042:9042
    ulimits:
      memlock: -1

#     Use this command to create the keyspace after starting of the Cassandra db
#     docker exec -it `docker ps | grep cassandra:3.11.8 | cut -b 1-12` cqlsh -e "create keyspace confeti WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };"
#
#     Use this command to check keyspaces
#     docker exec -it `docker ps | grep cassandra:3.11.8 | cut -b 1-12` cqlsh -e "describe keyspaces"
