spring:
  server:
    port: ${PORT}

confeti:
  cluster:
    webUrl: ${WEB_URL}
  cassandra:
    local: ${CONFETI_LOCAL_DB}
    session:
      name: ${CASSANDRA_SESSION_NAME}
      keyspace: ${CASSANDRA_KEYSPACE_NAME}
      rf: ${CASSANDRA_RF}
      durable: ${CASSANDRA_DURABLE}
