spring:
  server:
    port: ${PORT}

confeti:
  cluster:
    webUrl: ${WEB_URL}
  cassandra:
    local: false
    session:
      name: confeti_session
      keyspace: confeti
      rf: 1
      durable: true
