name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Push api to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./api/Dockerfile
          push: true
          tags: confeti/api:${{ steps.get_version.outputs.VERSION }},confeti/api:latest
      - name: Push web to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: confeti/web:${{ steps.get_version.outputs.VERSION }},confeti/web:latest

