name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Push api to Docker Hub
        uses: docker/build-push-action@v1
        with:
          context: ./
          file: ./api/Dockerfile
          repository: confeti/api:latest
      - name: Push api-astra to Docker Hub
        uses: docker/build-push-action@v1
        with:
          context: ./
          file: ./api/Dockerfile.astra
          repository: confeti/api-astra
          tag_with_ref: true
      - name: Push web to Docker Hub
          uses: docker/build-push-action@v1
          with:
            context: ./
            file: ./web/Dockerfile
            repository: confeti/web
            tag_with_ref: true
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: confeti/confeti/confeti
          tag_with_ref: true